runtime: go122  # Specify the Go version you're using

env_variables:
  FIREBASE_CREDENTIALS_FILE: ${FIREBASE_CREDENTIALS_FILE}
  PORT: "8080"

handlers:
- url: /.*
  script: auto

manual_scaling:
  instances: 1

instance_class: F1