runtime: go122  # Specify the Go version you're using

env_variables:
  FIREBASE_CREDENTIALS_FILE: ${FIREBASE_CREDENTIALS_FILE}
  PORT: "8080"

handlers:
- url: /.*
  script: auto

automatic_scaling:
  min_instances: 1
  max_instances: 5  # Adjust this based on your needs
  min_idle_instances: 1
  max_idle_instances: 1
  min_pending_latency: automatic
  max_pending_latency: automatic
  cpu_utilization:
    target_utilization: 0.9  # Adjust this value to control scaling

instance_class: F1

resources:
  cpu: 0.5
  memory_gb: 0.25
  disk_size_gb: 10
