name: Deploy to Google App Engine

on:
  push:
    branches:
      - main  # Set the branch to deploy from

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.22.4'  # Specify your Go version

    - name: Install dependencies
      run: go mod download

    - name: Run tests
      run: go test ./...

    - name: Deploy to Google App Engine
      run: gcloud app deploy
      env:
        GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
        GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
    - uses: google-github-actions/setup-gcloud@v2.1.0
      with:
        project_id: ${{ secrets.GCP_PROJECT }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
