name: Deploy to Google App Engine

on:
  push:
    branches:
      - main  # Set the branch to deploy from

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.22.4'  # Specify your Go version

    - name: Install dependencies
      run: go mod download

    - name: Run tests
      run: go test ./...

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2.1.0
      with:
        project_id: ${{ secrets.GCP_PROJECT }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Configure Firebase credentials
      run: |
        echo "${{ secrets.FIREBASE_CREDENTIALS }}" > $HOME/firebase-credentials.json
        echo "FIREBASE_CREDENTIALS_FILE=$HOME/firebase-credentials.json" >> $GITHUB_ENV

    - name: Deploy to Google App Engine
      env:
        GOOGLE_APPLICATION_CREDENTIALS: $HOME/firebase-credentials.json
      run: gcloud app deploy
