name: Deploy to Google App Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: app-engine

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.4'

    - name: Install dependencies
      run: go mod download

    - name: Create .env file
      run: |
        echo "FIREBASE_CREDENTIALS_FILE=placeholder" > .env
        echo "PORT=8080" >> .env

    - name: Run tests
      env:
        FIREBASE_CREDENTIALS_FILE: ${{ secrets.FIREBASE_CREDENTIALS_FILE }}
      run: go test ./...

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Deploy to Google App Engine
      run: |
        echo "${{ secrets.FIREBASE_CREDENTIALS_FILE }}" > /tmp/firebase_credentials.json
        gcloud app deploy app.yaml --quiet
      env:
        FIREBASE_CREDENTIALS_FILE: /tmp/firebase_credentials.json