name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: financial-data-platform-427521
  SERVICE_NAME: company-earnings-api
  REGION: us-central1

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: cloud-run

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
        service_account: 'my-service-account@my-project.iam.gserviceaccount.com'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Build and push Docker image
      env:
        DOCKER_IMAGE: gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
      run: |
        gcloud builds submit --tag $DOCKER_IMAGE

    - name: Deploy to Cloud Run
      env:
        DOCKER_IMAGE: gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
      run: |
        gcloud run deploy ${{ env.SERVICE_NAME }} \
          --image $DOCKER_IMAGE \
          --platform managed \
          --region ${{ env.REGION }} \
          --allow-unauthenticated \
          --set-env-vars FIREBASE_CREDENTIALS='${{ secrets.FIREBASE_CREDENTIALS_FILE }}' \
          --set-env-vars PORT=8080 \
          --cpu=1 \
          --memory=512Mi \
          --max-instances=5 \
          --min-instances=0 \
          --concurrency=80
